### ISSUE TITLE
Replace character with "a" does not work

### ISSUE THREAD

**Issue by seachicken** [inkdropapp/inkdrop-vim#11]
OS: macOS Catalina (10.15.3)
Inkdrop - keymap.cson: default

Pressing the "a" key after pressing the "r"(replace character) key in normal mode does not work.

**Comment by craftzdog** [comment]
Weird, will look into it.
Thanks for reporting!

**Comment by craftzdog** [comment]
fixed it and landed in v1.0.12 🎉

**Comment by seachicken** [comment]
Thank you :)
