### ISSUE TITLE
Plugin breaks Alfred snippet expansion

### ISSUE THREAD

**Issue by prurph** [inkdropapp/inkdrop-vim#12]
[Alfred](https://www.alfredapp.com/) is a popular OS X app. One of its features is snippets: you define a shortcut which, when typed, expands to some other text.

This functionality does not work inside of Inkdrop when the inkdrop-vim plugin is enabled.

One interesting note. If you:

1. Enter insert mode
2. Log out/in of macOS (this might [reset secure text entry?](https://www.alfredforum.com/topic/9796-secure-text-entry-locked/?do=findComment&comment=66333))
3. Snippets work temporarily

As soon as you exit insert mode and then re-enter it, snippets are broken again. I'm not too knowledgeable about how this works under the hood so I'm not sure if this is an easy fix or if the plugin/inkdrop can handle this somehow.

**Comment by craftzdog** [comment]
Thanks for the report.
Does it work here?

https://codemirror.net/demo/vim.html

If not, it would be hard to fix the issue by design.

**Comment by prurph** [comment]
Oh cool--didn't realize there was a demo site.

It does not work there. I'll just go ahead and close this since the issue seems tied to the use of codemirror.

**Comment by craftzdog** [comment]
Seems like so, unfortunately. Thanks for letting me know!

**Comment by prurph** [comment]
For anyone finding this later: I've discovered a workaround:

1. Enter insert mode
2. Alt+tab to another application, then back to Inkdrop (the editor should be in insert mode in the background at this time)
3. Snippets will work until you exit insert mode

This is actually pretty fast given you usually only need to use snippets sparingly.
