### ISSUE TITLE
Replace of any character with the character 'i' switches to insert mode instead

### ISSUE THREAD

**Issue by marksweiss** [inkdropapp/inkdrop-vim#15]
To reproduce:
* create text in `insert` mode in the editor window
* Press `ESC` to switch to `normal` mode
* Move the cursor over character you wish to replace
* Type the key combination `ri`

The result is that the character to be replaced remains, the mode has switched to `insert`, and the cursor is an insert cursor immediately to the right of the character to be replaced.

**Comment by marksweiss** [comment]
Note that the same bug occurs with the key combination `ra`, which exhibits identical behavior as described above.

**Comment by craftzdog** [comment]
Thanks for the report.
But it works as expected and I couldn't reproduce it.
Are you using the latest version? Please try `ipm update`.
I guess it is related to [this issue](https://github.com/inkdropapp/inkdrop-vim/issues/11).

**Comment by marksweiss** [comment]
I updated and the problem was fixed. You can close this. Thanks!

**Comment by craftzdog** [comment]
Ok!
