### ISSUE TITLE
Support `gj` and `gk` to move cursor through wrapped lines

### ISSUE THREAD

**Issue by jolyon129** [inkdropapp/inkdrop-vim#16]
Hi there,

Is it possible to add `gj` and `gk` motions to support move through wrapped lines?

It's a little painful to move around when I have a long paragraph without breaks.  
 
Ref: https://vim.fandom.com/wiki/Move_through_wrapped_lines 

Thanks.

**Comment by craftzdog** [comment]
Okay! Will be rolled out soon

**Comment by craftzdog** [comment]
Landed in v2.1.0🎉

**Comment by jolyon129** [comment]
After your new release, I add the following into my `keymap.cson` and now `j` and `k` always move by display line. 

```
'.CodeMirror.normal-mode textarea':
  'j': 'vim:move-down-by-display-lines'
  'k': 'vim:move-up-by-display-lines'
```
It works perfect for me. 😄

Again, thanks for your quick turnaround time.

**Comment by craftzdog** [comment]
Cool tip👍
