### ISSUE TITLE
Mark commands do not work

### ISSUE THREAD

**Issue by oniatsu** [inkdropapp/inkdrop-vim#18]
Mark commands look like not to work. Is it only on my PC?
https://github.com/inkdropapp/inkdrop-vim/blob/master/keymaps/vim.json#L85-L87

When I set other key to the commands, but the marking did not work in a similar way.

Other keybinds work correctly. (ex: `f` vim:find)

**Comment by craftzdog** [comment]
Oops, there are duplicate keybindings:

```
"\"": "vim:move-to-mark"
"\"": "vim:register-prefix"
```

`vim:move-to-mark` should be bound with `'` as the original CodeMirror implementation:

https://github.com/inkdropapp/inkdrop-vim/blob/master/src/keymap.js#L111

**Comment by craftzdog** [comment]
landed in v2.1.1🎉

**Comment by oniatsu** [comment]
Thank you for quick fix!
