### ISSUE TITLE
Write causes cursor to jump to beginning of note

### ISSUE THREAD

**Issue by brizzbuzz** [inkdropapp/inkdrop-vim#22]
👋  

Noticed a bug that has popped up recently where the `:w` command causes the cursor to jump to the beginning of my note. 

Not sure if this is a problem introduced in V5 or a conflict with another plugin I've installed, if it would be helpful to post any system/inkdrop information to assist in reproducing please let me know :)  

![example](https://user-images.githubusercontent.com/5607577/98122252-51156000-1e7e-11eb-8d40-1bd5fa4d7641.gif)

**Comment by craftzdog** [comment]
Hi,

Thanks for reporting it!
But I couldn't reproduce it.
I guess another plugin is causing it because vim plugin basically does nothing with the cursor on saving.

**Comment by brizzbuzz** [comment]
Interesting, will see what I can dig up!

**Comment by brizzbuzz** [comment]
looks like https://github.com/yaeda/inkdrop-prettier is the culprit, will investigate a bit and open up an issue in their repo :)

**Comment by craftzdog** [comment]
good to hear that you found it!
That makes sense. The plugin updates the note every time you save and that seems to cause the issue.

**Comment by brizzbuzz** [comment]
Yep, and the more I think about it, I'm not sure it is really a bug so much as a side effect... there is probably some work that could be done to make it play nicer with the vim plugin but effectively restructuring the page _could_ make maintaining cursor location tough

**Comment by craftzdog** [comment]
Agree if you want it to maintain cursor position strictly.
But at least, I guess it's enough to just remember the last cursor position because prettier basically doesn't make a big difference.
