### ISSUE TITLE
The motion `i` doesn't seem to work with text-objects '[' '(' when they represent links

### ISSUE THREAD

**Issue by rcashie** [inkdropapp/inkdrop-vim#23]
For example if I have a link 
```
[Hello World](https://helloworld.com)
```

With the cursor within either [ ... ] or (...), commands `ci)` or `di]` do not seem to work. 

Typically all content within the brackets are removed (and I'm put into insert mode if the command is `c` / change)

**Comment by craftzdog** [comment]
Fixed in v2.1.4. Thanks!
