### ISSUE TITLE
Number arguments dont seem to work with line-based motions

### ISSUE THREAD

**Issue by rcashie** [inkdropapp/inkdrop-vim#24]
For example:

Delete 5 lines
`4d`

Yank 3 lines
`2y`

**Comment by craftzdog** [comment]
You have to type `4dd` and `2yy`

**Comment by rcashie** [comment]
Thanks for the reply @craftzdog I can definitely use those commands :)

I think I left out that after typing `4d` or `2y` I hit `enter`. I'm not sure why that works in other vim utils but it does. It works in the codemirror vim bindings demo here -> https://codemirror.net/demo/vim.html as well

**Comment by craftzdog** [comment]
Ah makes sense. on it

**Comment by craftzdog** [comment]
landed in v2.1.5! Thanks
