### ISSUE TITLE
'Ctrl-[' not working on Windows 

### ISSUE THREAD

**Issue by sarchotic** [inkdropapp/inkdrop-vim#26]
Hello, 
It doesn't appear that 'Ctrl-[' remaps the esc key for vim in inkdrop. 

I've placed the following command in my keymap file but the command still does not work: 
```
{
  ".CodeMirror.vim-mode.normal-mode textarea": {
    "ctrl-[": "vim-mode: reset-normal-mode"
  }
}
```

For reference the keyboard I am using is an HHKB Hybrid Type-S with a standard ANSI layout. 

Thank you

**Comment by craftzdog** [comment]
Hi.
`vim-mode: reset-normal-mode` is not correct. Do not insert a space after the colon.

```
{
  ".CodeMirror.vim-mode.normal-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.insert-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.replace-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.visual-mode textarea": {
    "ctrl-[": "vim:exit-visual-mode",
  }
}
```

**Comment by hideakitai** [comment]
Hi @craftzdog , thank you for the great app!
I had the same problem on Windows. My keyboard is [RealForce UB87](https://www.realforce.co.jp/en/products/87UB_SE17T0/) and it's a US keyboard. Replacing `ctrl-[` to `j j` also didn't work... Do you have any idea for this?

``` keymap.cson
{
  '.CodeMirror textarea': {
    'ctrl-[': "false",
    'ctrl-]': "false"
  },
  ".CodeMirror.vim-mode.normal-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.insert-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.replace-mode textarea": {
    "ctrl-[": "vim:reset-normal-mode"
  },
  ".CodeMirror.vim-mode.visual-mode textarea": {
    "ctrl-[": "vim:exit-visual-mode"
  }
}
```

![image](https://user-images.githubusercontent.com/889950/134837387-0922c324-0611-4ea9-bc00-f932f9ec1119.png)

**Comment by craftzdog** [comment]
Hi,

The commands are different for the other modes. Can you please try the following keymap?:

```json
  ".CodeMirror.vim-mode.insert-mode textarea": {
    "ctrl-[": "vim:exit-insert-mode"
  },
  ".CodeMirror.vim-mode.replace-mode textarea": {
    "ctrl-[": "vim:exit-insert-mode"
  },
  ".CodeMirror.vim-mode.visual-mode textarea": {
    "ctrl-[": "vim:exit-visual-mode"
  }
```

Ref: https://github.com/inkdropapp/inkdrop-vim/blob/master/keymaps/vim.json#L145

**Comment by hideakitai** [comment]
Wow, worked perfectly... Thank you so much!

**Comment by craftzdog** [comment]
Great!
