### ISSUE TITLE
How can I create Ex commands? 

### ISSUE THREAD

**Issue by ghost** [inkdropapp/inkdrop-vim#27]
I wanna create some ex commands to inkdrop commands like :f to core:find-global as I use in vim.

**Comment by craftzdog** [comment]
I'm afraid that Ex commands are hard-coded and can't be customized.

https://github.com/inkdropapp/inkdrop-vim/blob/master/src/vim.js#L958

**Comment by ghost** [comment]
Is there any alternatives to put some global object that is customizable through a cson file like keymaps?

**Comment by craftzdog** [comment]
You can write `init.js` like so:

```js
inkdrop.onEditorLoad(() => {
	var CodeMirror = require('codemirror')
	CodeMirror.Vim.defineEx('find', 'f', (cm, event) => {
	  inkdrop.commands.dispatch(document.body, 'core:find-global')
	  if (event.argString) inkdrop.commands.dispatch(document.body, 'core:search-notes', { keyword: event.argString.trim() })
	})	
})
```

**Comment by ghost** [comment]
It worked! Thanks
