### ISSUE TITLE
bug : "cw" delete a line on cursor

### ISSUE THREAD

**Issue by ShoMasegi** [inkdropapp/inkdrop-vim#3]
## Environment

version - 0.3.1

## Bug

**Expected Result :** delete the characters of the word from the cursor, and enter insert-mode.

**Actual Result :**  delete the line on cursor, and enter insert-mode.

Please fix it. :bow:

**Comment by craftzdog** [comment]
Got it, I will look into it.
Thank you for the report!

**Comment by craftzdog** [comment]
I believe v0.3.2 should fix this problem. Thanks.
