### ISSUE TITLE
Key binding for toggle preview mode in vim command mode

### ISSUE THREAD

**Issue by hakonhagland** [inkdropapp/inkdrop-vim#31]
When in vim command mode, `CTRL+E` does not work to switch to preview mode (it works fine in insert mode). Instead it runs the command "move screen down one line (without moving cursor)". Is there a way to disable this behavior or to set an alternative keybinding for `view::toggle-preview` when in vim command mode?

**Comment by craftzdog** [comment]
Yes, you can set keybindings for the insert mode with this selector: `.CodeMirror.vim-mode.insert-mode textarea`

https://github.com/inkdropapp/inkdrop-vim#key-customizations
