### ISSUE TITLE
Support for Ctrl-[

### ISSUE THREAD

**Issue by jcredmond** [inkdropapp/inkdrop-vim#38]
I understand it's not feasible to have Inkdrop parse my .vimrc, but supporting the standard Ctrl-[ (does the same thing as Esc) would be awesome. Thanks!

**Comment by craftzdog** [comment]
You can customize keymaps as you like. Please read the documentation:

- https://docs.inkdrop.app/manual/customizing-keybindings
- https://github.com/inkdropapp/inkdrop-vim#key-customizations
