### ISSUE TITLE
Support for G/gg

### ISSUE THREAD

**Issue by jamalmoir** [inkdropapp/inkdrop-vim#39]
It would be great to be able to do things such as yG/ygg/dG/dgg.

Currently it doesn't seem like we can do it and selecting whole documents and such is a little difficult.

**Comment by craftzdog** [comment]
yeah looks like those motions are not properly handled when key buffering.

**Comment by craftzdog** [comment]
I guess I managed to solve this.
Can you try the current master branch with `ipm install inkdropapp/inkdrop-vim`?

**Comment by craftzdog** [comment]
no response

**Comment by jamalmoir** [comment]
Hey, thanks for the fix, it's working nicely!

Sorry for the late reply, my github notifications are too busy to be able to catch individual ones like this.

**Comment by craftzdog** [comment]
Great, thanks for letting me know!
