### ISSUE TITLE
substitute "s" does not work

### ISSUE THREAD

**Issue by gregwebs** [inkdropapp/inkdrop-vim#4]
Shift + "s" does not work for me either. This key is bound in the default configuration for this plugin.

**Comment by craftzdog** [comment]
That's a bug. Thanks!

**Comment by giantsol** [comment]
Hi!
I just ipm installed this package today and tried "s" or "shift-s", but I guess substitute isn't working..
Could you have a look at it?
Thank you in advance :)

**Comment by craftzdog** [comment]
Fixed in v1.0.7. Thanks!
