### ISSUE TITLE
App crashes on startup due to vim keybinding setting

### ISSUE THREAD

**Issue by PhilBookst** [inkdropapp/inkdrop-vim#44]
Hey, suddenly my app crashes on startup due to a vim keybinding. Since I can't access the app, i cannot change the vim config file. Where is this file stores so I can go in there manually?

Thanks!

```
Error: Failed to load global keymaps. Please make sure if the syntax is correct: YAMLParseError - Tabs are not allowed as indentation at line 2, column 1:

'.CodeMirror.vim-mode.insert-mode textarea':
'j k': 'vim:exit-insert-mode'
^

at Se.start (/Applications/Inkdrop.app/Contents/Resources/app.asar/main.js:1:74656)
at z (/Applications/Inkdrop.app/Contents/Resources/app.asar/main.js:1:111726)
at /Applications/Inkdrop.app/Contents/Resources/app.asar/main.js:1:126281
Please check your configuration.
```

**Comment by craftzdog** [comment]
Can you please check out the documentation?
https://docs.inkdrop.app/manual/customizing-keybindings
The files can be found here
https://docs.inkdrop.app/manual/basic-usage#user-data-directory
