### ISSUE TITLE
vim motion doesn't work while typing in Japanese...

### ISSUE THREAD

**Issue by tsoumdoa** [inkdropapp/inkdrop-vim#46]
The plugin doesn't let me enter an insert mode from normal mode when I'm typing in Japanese. It would be huge for me if it could be done... 

I'm using it on M1 MBP with Sonoma 14.5.

**Comment by craftzdog** [comment]
Unfortunately, it is by design. You can reproduce the issue here: https://codemirror.net/5/demo/vim.html
I hope it will be solved when migrating to CM6, which is planned in the future.

**Comment by tsoumdoa** [comment]
I c, noted. Thank you for getting back on this!  really hope so too...!
