### ISSUE TITLE
CTRL+[ not working

### ISSUE THREAD

**Issue by fkjctm** [inkdropapp/inkdrop-vim#6]
Inkdrop Version: 3.23.1
OS: Ubuntu 18.04

My escape sequence is `CTRL+[` which was not working by default. I had to add the following to keymap.cson to get it to work:

```
{
  ".CodeMirror.vim-mode.insert-mode textarea": {
    "ctrl-[": "vim-mode:exit-insert-mode"
  }
}
```

**Comment by craftzdog** [comment]
Hi @agvctm,

Thanks for reporting.
This should be a keyboard setting problem because `ctrl-[` is natively mapped to `esc` by default on Linux. I got it to work without the keymap setting.

**Comment by fkjctm** [comment]
Interesting. I do swap my left control key with caps lock, but I can't get it to escape when using the right control key either. I don't have a problem in any other vim emulator (Ideavim) either. I'll go ahead and close this issue.

**Comment by kato1628** [comment]
The following keymap setting worked at least on my macOS environment. Maybe `vim-mode:` should be `vim:`.

```json
{
  ".CodeMirror.vim-mode.insert-mode textarea": {
    "ctrl-[": "vim:exit-insert-mode"
  }
}
```

**Comment by craftzdog** [comment]
Thanks @kato1628. Btw, I'm using Karabiner Elements to map it.
