### ISSUE TITLE
Escape remap to 'jj'

### ISSUE THREAD

**Issue by rtmor** [inkdropapp/inkdrop-vim#8]
Remapping escape to 'jj' to exit insert mode works well, however, the 'j' character can not be used while in insert mode.  No 'j'.

Any way around this?  It's an important feature to me.

Thanks very much

**Comment by craftzdog** [comment]
That'd be a bug. On it.

**Comment by craftzdog** [comment]
Can you please try 1.0.9?

**Comment by rtmor** [comment]
Thank you!

It appears to be fixed.

**Comment by craftzdog** [comment]
Great! Thank you for reporting.
